# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 主题重定义配置文件 V2
# 作者：EvanNotFound
# GitHub: https://github.com/EvanNotFound/hexo-theme-redefine
# 文档: https://redefine-docs.ohevan.com
# 演示: https://redefine.ohevan.com
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 基本信息 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/info
info:
  # 网站标题
  title: YanMoBlog
  # 作者名字
  author: YanMo
  # 网站 URL
  url: https://blog.ymbit.cn/
# 基本信息 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 图片配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/defaults
defaults:
  # 网站图标
  favicon: 'https://cravatar.cn/avatar/d03f4b96830060cab36b44646cf426e3'
  # 网站 logo
  logo: 'https://cravatar.cn/avatar/d03f4b96830060cab36b44646cf426e3'
  # 网站头像
  avatar: 'https://cravatar.cn/avatar/d03f4b96830060cab36b44646cf426e3'
# 图片配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 颜色 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/colors
colors:
  # 主色
  primary: "#A31F34"
  # 辅助色 (待定)
  secondary:
  # 默认主题模式初始值 (将被 prefer-color-scheme 覆盖)
  default_mode: light # light, dark
# 颜色 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 网站自定义 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/global
global:
  # 自定义全局字体
  fonts:
    # 中文字体
    chinese: 
      enable: false # 是否启用自定义中文字体
      family:  # 字体家族
      url:  # 字体 CSS 文件的 URL
    # 英文字体
    english: 
      enable: false # 是否启用自定义英文字体
      family:  # 字体家族
      url:  # 字体 CSS 文件的 URL
    # 自定义标题字体（导航栏、侧边栏）
    title:
      enable: false # 是否启用自定义标题字体
      family:  # 字体家族
      url:  # 字体 CSS 文件的 URL
  # 内容最大宽度
  content_max_width: 1000px
  # 侧边栏宽度
  sidebar_width: 210px
  # 鼠标悬停效果
  hover:
    shadow: true # 阴影效果
    scale: false # 缩放效果
  # 滚动进度
  scroll_progress:
    bar: false # 进度条
    percentage: true # 百分比
  # 网站计数器
  website_counter:
    url: https://cn.vercount.one/js # 计数器 API URL (无需更改)
    enable: true # 是否启用网站计数器
    site_pv: true # 网站页面浏览量
    site_uv: true # 网站独立访客
    post_pv: true # 文章页面浏览量
  # 是否启用单页体验（使用 swup）。参见 https://swup.js.org/，类似于 pjax
  single_page: true
  # 是否启用加载动画。
  preloader:
    enable: false
    custom_message: # 自定义消息。如果为空，网站标题将显示
  # 是否启用开放图
  open_graph: true
  # 谷歌分析
  google_analytics:
    enable: true # 是否启用 Google Analytics
    id:  # Google Analytics 测量 ID
# 网站自定义 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
    
# FontAwesome >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/fontawesome
fontawesome: # Pro v6.2.1
  # 细版
  thin: false
  # 轻版
  light: false
  # 双音版
  duotone: false
  # 锐利实心版
  sharp_solid: false
# FontAwesome <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 首页横幅 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/home/home_banner
home_banner:
  # 是否启用首页横幅
  enable: true
  # 首页横幅样式
  style: fixed # 静态或固定
  # 首页横幅图片
  image: 
    light: /images/wallhaven-wqery6-light.webp # 明亮模式
    dark: /images/wallhaven-wqery6-dark.webp # 暗黑模式
  # 首页横幅标题
  title: YanMoBlog
  # 首页横幅副标题
  subtitle:
    text: ['事情总是走向最差的一面，人总是活成自己讨厌的样子'] # 副标题文本，数组
    hitokoto:  # 一言配置
      enable: false # 是否启用一言
      show_author: false # 是否显示作者
      api: https://v1.hitokoto.cn # API URL，可以添加类型，参见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    typing_speed: 100 # 打字速度（毫秒）
    backing_speed: 80 # 回退速度（毫秒）
    starting_delay: 500 # 开始延迟（毫秒）
    backing_delay: 1500 # 回退延迟（毫秒）
    loop: true # 是否循环
    smart_backspace: true # 是否智能回退
  # 首页横幅文本颜色
  text_color: 
    light: "#fff" # 明亮模式
    dark: "#d1d1b6" # 暗黑模式
  # 文本特定样式
  text_style: 
    # 标题字体大小
    title_size: 2.8rem
    # 副标题字体大小
    subtitle_size: 1.5rem
    # 标题与副标题之间的行高
    line_height: 1.2
  # 首页横幅自定义字体
  custom_font: 
    # 是否启用自定义字体
    enable: false
    # 字体家族
    family: 
    # 字体 CSS 文件的 URL
    url:
  # 首页横幅社交链接
  social_links:
    # 是否启用
    enable: false
    # 社交链接样式
    style: default # default, reverse, center
    # 社交链接
    links:
      github: https://github.com/ltzXiaoYanMo # 你的 GitHub URL
      instagram: # 你的 Instagram URL
      zhihu:  # 你的 ZhiHu URL
      twitter:  # 你的 Twitter URL
      email:  # 你的邮箱
      # ...... # 你可以添加更多
    # 带二维码的社交链接
    qrs:
      weixin:  # 你的微信二维码图片 URL
      # ...... # 你可以添加更多
# 首页横幅 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 导航栏 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/home/navbar
navbar:
  # 自动隐藏导航栏
  auto_hide: false
  # 导航栏背景颜色
  color:
    left: "#f78736" # 左侧 
    right: "#367df7"  # 右侧
    transparency: 35 # 百分比 (10-99)
  # 导航栏宽度（通常无需修改）
  width:
    home: 1200px # 首页
    pages: 1000px # 其他页面
  # 导航栏链接
  links:
    Home: 
      path: / 
      icon: fa-regular fa-house # 可以为空
    Links: 
      path: /links 
      icon: fa-regular fa-link
    Status: 
      path: https://status.ymbit.cn/status/ymstatus
      icon: fa-regular fa-chart-bar
    About: 
      path: /about
      icon: fa-regular fa-user
    # Links: 
    #   icon: fa-regular fa-link
    #  


# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.ymbit.cn
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: []
exclude: []
ignore: 

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: redefine

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
