name: Deploy

on:
  push:
    branches:
      - master

jobs:
  DeployServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm  # 确保缓存 pnpm 依赖
      - name: Cache PNPM dependencies
        uses: actions/cache@v4
        with:
          path: .pnpm-store
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Rsync Files
        uses: contention/rsync-deployments@v2.0.0
        with:
          HOST: ${{ secrets.HOSTS }}
          USER: github_deploy_user
          LOCALPATH: ./public/
          REMOTEPATH: /opt/1panel/apps/openresty/openresty/www/sites/blog.ymbit.cn/index/
          FLAGS: -avz
          DEPLOY_KEY: ${{ secrets.RSYNC_PASSPHRASE }}
