name: deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and execute command
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /root/blog-source
            bash scripts/update.sh
          host: ${{ secrets.HOSTS }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22